site_name: CoreProtect Documentation
site_url: https://docs.coreprotect.net/
theme: readthedocs
repo_url: https://github.com/PlayPro/CoreProtect
nav:
    - Home: index.md
    - Configuration: config.md
    - Commands: commands.md